[versions]
kotlin = "2.2.21"
ktor = "3.3.3"
log4j2 = "2.25.3"
ksp = "2.2.21-2.0.4"
dagger = "2.57"

caffeine = "3.2.3"

openai-java = "4.12.0"
ktoml-core = "0.7.1"

kotlinx-coroutines = "1.10.2"
kotlinx-serialization = "1.8.1"
license-report = "2.9"
node-gradle = "7.1.0"

# Testing
junit-jupiter = "5.14.1"
junit-platform = "1.14.1"
kotlinx-coroutines-test = "1.10.2"
mockk = "1.13.13"
turbine = "1.1.0"

[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
ktor = { id = "io.ktor.plugin", version.ref = "ktor" }
dependency-license-report = { id = "com.github.jk1.dependency-license-report", version.ref = "license-report" }
node-gradle = { id = "com.github.node-gradle.node", version.ref = "node-gradle" }

[libraries]
kotlin-stdlib = { group = "org.jetbrains.kotlin", name = "kotlin-stdlib", version.ref = "kotlin" }
kotlin-reflect = { group = "org.jetbrains.kotlin", name = "kotlin-reflect", version.ref = "kotlin" }

kotlinx-coroutines = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-core", version.ref = "kotlinx-coroutines" }
kotlinx-serialization-json = { group = "org.jetbrains.kotlinx", name = "kotlinx-serialization-json", version.ref = "kotlinx-serialization" }

dagger = { group = "com.google.dagger", name = "dagger", version.ref = "dagger" }
dagger-compiler = { group = "com.google.dagger", name = "dagger-compiler", version.ref = "dagger" }
javax-inject = { group = "javax.inject", name = "javax.inject", version = "1" }

caffeine = { group = "com.github.ben-manes.caffeine", name = "caffeine", version.ref = "caffeine" }

openai-java = { group = "com.openai", name = "openai-java", version.ref = "openai-java" }
ktoml-core = { group = "com.akuleshov7", name = "ktoml-core", version.ref = "ktoml-core" }

ktor-bom = { module = "io.ktor:ktor-bom", version.ref = "ktor" }

ktor-server-core = { module = "io.ktor:ktor-server-core" }
ktor-server-websockets = { module = "io.ktor:ktor-server-websockets" }
ktor-server-content-negotiation = { module = "io.ktor:ktor-server-content-negotiation" }
ktor-serialization-kotlinx-json = { module = "io.ktor:ktor-serialization-kotlinx-json" }
ktor-serialization-gson = { module = "io.ktor:ktor-serialization-gson" }
ktor-server-caching-headers = { module = "io.ktor:ktor-server-caching-headers" }

ktor-server-rate-limit = { module = "io.ktor:ktor-server-rate-limit" }
ktor-server-host-common = { module = "io.ktor:ktor-server-host-common" }
ktor-server-status-pages = { module = "io.ktor:ktor-server-status-pages" }
ktor-server-call-logging = { module = "io.ktor:ktor-server-call-logging" }
ktor-server-request-validation = { module = "io.ktor:ktor-server-request-validation" }
ktor-server-sessions = { module = "io.ktor:ktor-server-sessions" }
ktor-server-cors = { module = "io.ktor:ktor-server-cors" }
ktor-server-netty = { module = "io.ktor:ktor-server-netty" }
ktor-server-config-yaml = { module = "io.ktor:ktor-server-config-yaml" }
ktor-server-test-host = { module = "io.ktor:ktor-server-test-host" }

ktor-client-content-negotiation = { module = "io.ktor:ktor-client-content-negotiation" }
ktor-client-websockets = { module = "io.ktor:ktor-client-websockets" }

mockk = { group = "io.mockk", name = "mockk", version.ref = "mockk" }
turbine = { group = "app.cash.turbine", name = "turbine", version.ref = "turbine" }

log4j-bom = { module = "org.apache.logging.log4j:log4j-bom", version.ref = "log4j2" }
log4j-core = { module = "org.apache.logging.log4j:log4j-core" }
log4j-slf4j2-impl = { module = "org.apache.logging.log4j:log4j-slf4j2-impl" }

kotlin-test-junit = { module = "org.jetbrains.kotlin:kotlin-test-junit", version.ref = "kotlin" }
kotlin-test-junit5 = { module = "org.jetbrains.kotlin:kotlin-test-junit5", version.ref = "kotlin" }
kotlinx-coroutines-test = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-test", version.ref = "kotlinx-coroutines-test" }
junit-jupiter = { module = "org.junit.jupiter:junit-jupiter", version.ref = "junit-jupiter" }
junit-platform-launcher = { module = "org.junit.platform:junit-platform-launcher", version.ref = "junit-platform" }
